name: Apply
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Running TF Apply
        env:
          TF_VAR_token: ${{ secrets.TOKEN }}
        run: |
          cd roboshop-v1
          make dev-apply token=${TF_VAR_token}