name: Destroy
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Running Init
        run: |
          cd roboshop-v1
          terraform init --backend-config=./env/dev/state.tfvars
          
      - name: Running Plan
        env:
          TF_VAR_token: ${{ secrets.TOKEN }}
        run: |
          cd roboshop-v1
          terraform plan --var-file=env/dev/main.tfvars -var token=${{ secrets.TOKEN }}

      - name: Running Apply
        env:
          TF_VAR_token: ${{ secrets.TOKEN }}
        run: |
          cd roboshop-v1
          terraform destroy -auto-approve --var-file=env/dev/main.tfvars -var token=${{ secrets.TOKEN }}          